site_name: Waves'N See calib tool
site_description: A python tool to compute intrinsic camera parameters
docs_dir: src

nav:
  - ğŸ  Home: index.md
  - ğŸ–¥ CLI: cli.md
  - ğŸ¥ Acquisition: mode-acquisition.md
  - ğŸ›  Hardware:
      - ğŸ–¥ NUC 11: installation-nuc11.md
      - ğŸ“ Raspberry PI: installation-raspberry-pi.md
      - ğŸ¥ Axis: config_axis.md
      - ğŸ“– Historique: installations-historique.md
  - â“FAQ: faq.md

theme:
  name: material
  logo: img/box_unicode.png
  favicon: img/box_unicode.ico

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow


extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html